import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  const cdnBase = process.env.NEXT_PUBLIC_LANDING_ASSETS_CDN_BASE;
  const interDisplayUrl = `${cdnBase}/get-featured/inter-display/InterVariable.ttf`;
  const interUrl = `${cdnBase}/get-featured/Inter/Inter-VariableFont_opsz,wght.ttf`;

  return (
    <html
      lang="en"
      className="font-inter h-full antialiased"
    >
      <head>
        <style dangerouslySetInnerHTML={{
          __html: `
            @font-face {
              font-family: 'Inter Display';
              src: url('${interDisplayUrl}') format('truetype');
              font-display: swap;
            }
            @font-face {
              font-family: 'Inter';
              src: url('${interUrl}') format('truetype');
              font-display: swap;
            }
            :root {
              --font-inter-display: 'Inter Display', sans-serif;
              --font-inter: 'Inter', sans-serif;
            }
          `
        }} />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
